---
- name: Install prerequisites
  hosts:
  - nodes
  - localhost
  gather_facts: true
  tags:
  - never
  - prerequisites
  tasks:
  - name: install netcat
    become: yes
    package:
      name: nmap-ncat
      state: present

- import_playbook: tasks/ocp_3-11_flows.yml

- name: Display results
  hosts: localhost
  tasks:
  - name: Successfull checks
    debug:
      msg: "{{ query('flattened',query('dict',hostvars) | selectattr('value.flow_checks', 'defined') | map(attribute='value.flow_checks') | list) | selectattr('status') | map(attribute='rule') | list }}"
  - name: Failed checks
    debug:
      msg: "{{ query('flattened',query('dict',hostvars) | selectattr('value.flow_checks', 'defined') | map(attribute='value.flow_checks') | list) | rejectattr('status') | map(attribute='rule') | list }}"
    failed_when: query('flattened',query('dict',hostvars) | selectattr('value.flow_checks', 'defined') | map(attribute='value.flow_checks') | list) | rejectattr('status') | map(attribute='rule') | list | length > 0
